### ISSUE TITLE
get sync always return true 

### ISSUE THREAD

**Issue by windmaomao** [flosse/json-file-store#5]
if i call db.getSync(id), seems to me no matter what, I'm getting a record back. However this doesn't happen to get(id, function(err)) which gives the correct behavior.

**Comment by flosse** [comment]
> if i call db.getSync(id), seems to me no matter what, I'm getting a record back.

yes, if the record exists, you'll get the record back otherwise an error

> However this doesn't happen to get(id, function(err))
`get` is an asynchronous method, so you'll always get `undefined` as return value but the callback function takes two parameters, an error and the record.

> which gives the correct behavior.

what do you mean by "correct behavior"? What do you think is correct and what is wrong?

**Comment by windmaomao** [comment]
i could be wrong, but last time i tried, db.getSync(id) will return a record with 
{id : id } 
even when id doesn't exist.

**Comment by flosse** [comment]
I can't reproduce this behavior. Could you try it again and write the steps down?

**Comment by flosse** [comment]
please reopen if this is still an issue
